# Default values for fluent-bit.

image:
  repository: fluent/fluent-bit
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

rbac:
  create: true

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 2020
  annotations: {}
    # prometheus.io/path: "/api/v1/metrics/prometheus"
    # prometheus.io/port: "2020"
    # prometheus.io/scrape: "true"

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

priorityClassName: ""

env: []

envFrom: []

extraVolumes: []

extraVolumeMounts: []

config:
  ## Ref: https://docs.fluentbit.io/manual/service
  service:
    Flush: 1
    Daemon: Off
    Log_Level: info
    Parsers_File: parsers.conf
    Parsers_File: custom_parsers.conf
    HTTP_Server: On
    HTTP_Listen: 0.0.0.0
    HTTP_Port: 2020

  ## Ref: https://docs.fluentbit.io/manual/input
  inputs:
    - Name: tail
      Path: /var/log/containers/*.log
      Parser: docker
      Tag: kube.*
      Mem_Buf_Limit: 5MB
      Skip_Long_Lines: On
    - Name: systemd
      Tag: host.*
      Systemd_Filter: _SYSTEMD_UNIT=kubelet.service
      Read_From_Tail: On

  ## Ref: https://docs.fluentbit.io/manual/filter
  filters:
    - Name: kubernetes
      Match: kube.*
      Merge_Log: On
      Keep_Log: Off
      K8S-Logging.Parser: On
      K8S-Logging.Exclude: On

  ## Ref: https://docs.fluentbit.io/manual/output
  outputs:
    - Name: es
      Match: "*"
      Host: elasticsearch-master
      Logstash_Format: On
      Retry_Limit: False

  ## Ref: https://docs.fluentbit.io/manual/parser
  customParsers: []
    # - Name: docker_no_time
    #   Format: json
    #   Time_Keep: Off
    #   Time_Key: time
    #   Time_Format: "%Y-%m-%dT%H:%M:%S.%L"
